apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysqlfinal-pvc
  namespace: production
  #annotations:
  #  volume.beta.kubernetes.io/storage-class: {{ .Values.persistence.storageClass }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClass }}

