apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql
  namespace: production
  labels:
    app: wordpressmysql
spec:
  ports:
    - port: 3306
  selector:
    app: wordpressmysql
    tier: mysql
  clusterIP: None

