apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-wordpress
  namespace: production
  labels: 
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: {{ .Values.image.repository }}
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: {{ .Values.mysql.host }}
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.mysql.secretName }}
              key: {{ .Values.mysql.secretKey }}
        - name: WORDPRESS_DB_USER
          value: {{ .Values.mysql.user }}
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
          requests:
            cpu: {{ .Values.resources.requests.cpu }}    
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wordpress-pv
          mountPath: /var/www/html/
      volumes:
      - name: wordpress-pv
        persistentVolumeClaim:
          claimName: worpressfinal-pvc

