apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: worpressfinal-pvc
  namespace: production
  # annotations:
  # volume.beta.kubernetes.io/storage-class: {{ .Values.persistence.storageClass }}
  labels:
    app: wordpress
spec:
  accessModes:
  - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClass }}

