apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysql-pass
  namespace: production
spec:
  encryptedData:
    password: AgAyWDvSCLEDqV7QurzwjU3/4m2nP+epAgd3wsypaGnC6HUFYJIea+7c2H29T1Wd29nOUJrhwB5Ux6HDwVcDR8BoKT5cRI2AIHgv9F0H6WEIScpqIhfE8SKzcTQyy2b0OsAL4FIOL/bAc5Z0DcMd5nTc9jTZXTu5F3ziS3vNytiIDwf8F4diyi3EE4TqSa8InOnAoo7I4Zd73+DMwjXWDDcpp1W1kodB/FU4B4TQfQBLaOQYU88u/ncug2WJIPFnP7kEw4gX9Dfq4mlkDau9qef6QRwcvEr3JTbppQrqeLcxOdrWum8d6+Tswud3p7pNX9Ko/A73saQaA53zygu0q3rn6758ze5WbqHHWmctuESpXqS6MMJ59+Ncdm1fkgMBbxoVjNkPiF1fSgknGeYef73kHUBAvwnC+w4fIRN/qLXvDuNu7ROhKaOAIWKm7rIy7ApiOdHxXxl4XSS2fiKvx9gIz/85tGeKuWMOX3aY6yoXeiPVlKGyEFAt3/fgrmESfuvqQIVxTRO/G4qTM3LziyVmqqO9EAW+XhRfp/X3qqUfDIeNLcbQymD18NMSoV9IwZkuQHCUXRpnaHR3Ych4/+lYjltytHS5S8V43puUoJWXAe+MCqpjLfXzQkj/XUjhhRgD46KJNN6qSNB18LUvX6Bil0QKEMLXv/50EJojdNqc5UhUfobnfGF5yZnJ+2iHb0MBXkWq9JCGIw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      labels:
        app: wordpress
      name: mysql-pass
      namespace: production
    type: Opaque

