apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mysql.secretName }}
  namespace: production
  labels: 
    app: wordpress
type: Opaque
data:
  {{ .Values.mysql.secretKey }}: {{ .Values.mysql.secretValue | b64enc }}

